export const PRE_REGISTRATION_PRIVACY_VERSION = "2026-07-19";
export const PRE_REGISTRATION_NOTE_MAX_LENGTH = 1000;
export const PRE_REGISTRATION_MIN_AGE = 5;
export const PRE_REGISTRATION_MAX_AGE = 20;
